version: "3.8"
services:
  cuchi-gis-web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rm -rf public/assets public/packs && bundle exec rake assets:precompile && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - /root/projects/cuchi/web-app-files:/app_files
    ports:
      - "3015:3000"
    restart: always
    networks:
      - cuchi-gis-network
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
networks:
  cuchi-gis-network:
    external: true
